version: "3"
services:
  # ahora se indican los servicios por el orden en que se quiere que se inicien.
  # Por ejemplo, mongo debe estar antes de order.
  # mongo: mismo nombre usado en el run.sh de Order y application.properties. # Se resuelve en una direcci√≥n IP.
  web:
    image: ivanvc03/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
      #    memory: 300M
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost
    ports:
      - "80:8080"

  mongo:
    image: ivanvc03/p2gps:db
    deploy:
      replicas: 1 # para escalabilidad del servicio.
      resources:
        limits:
          cpus: "0.15"
       #   memory: 200M
    ports:
      - "28017:28017"
      - "27017:27017"
    volumes:
      - "db-data:/data/db" # para guardar en local los cambios en el contenedor

  order:
    image: ivanvc03/p2gps:order
    depends_on:
      - "mongo" # le pasamos al servicio order la IP del servicio mongo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
        #  memory: 500M
    ports:
      - "8080:8080"
    

volumes:
  db-data: