name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # descarga el repositorio en el ejecutor

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }} # ubicaci√≥n para el archivo settings.xml

      #### BUILDS ####
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 2.1

      - name: Build del Front
        working-directory: src/Clients
        run: ./gradlew build

      - name: Upload Front Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clients
          path: src/Clients/build/libs

      - name: Build del Back
        working-directory: src/Backend/OrderService
        run: ./gradlew build test
